### ISSUE TITLE
Declaration incompatible

### ISSUE THREAD

**Issue by lollita** [aVadim483/fast-excel-templator#1] opened 2023-11-01 18:22 UTC
when I use:
```
require 'FastExcelReader/autoload.php';
use \avadim\FastExcelReader\Excel as ExcelReader;
require 'FastExcelWriter/autoload.php';
use \avadim\FastExcelWriter\Excel as ExcelWriter;
require 'FastExcelTemplator/autoload.php';
use \avadim\FastExcelTemplator\Excel as ExcelTemplator;
$excel = ExcelTemplator::template('./test/file1.xlsx', './test/file2.xlsx');
```

I get:

> Declaration of avadim\FastExcelTemplator\Excel::createSheet(string $sheetName, $sheetId, $file, $path, $excel): avadim\FastExcelTemplator\Sheet must be compatible with avadim\FastExcelReader\Excel::createSheet(string $sheetName, $sheetId, $file, $path): avadim\FastExcelReader\Sheet

How to solve?

**Comment by lollita** [comment] 2023-11-01 20:17
I solved installing from composer instead of manually.
Now I get:
Uncaught Exception: Errore (Codice 2) - XMLReader::open(zip://C:\Test\Test.xlsx#xl/worksheets/sheet4.xml): Failed to open stream: operation failed in C:\Test\vendor\avadim\fast-excel-reader\src\FastExcelReader\Reader.php linea 110 in K:\Gemma\common.php:14

zip module enabled and working in windows.

**Comment by lollita** [comment] 2023-11-01 21:30
With other file I get:

> <b>Fatal error</b>:  During inheritance of Iterator: Uncaught Exception: Errore (Codice 8192) - Return type of avadim\FastExcelTemplator\RowTemplate::current() should either be compatible with Iterator::current(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\test\vendor\avadim\fast-excel-templator\src\FastExcelTemplator\RowTemplate.php linea 71

**Comment by aVadim483** [comment] 2023-11-02 06:38
@lollita what is version of php?

**Comment by lollita** [comment] 2023-11-02 06:39
8.2.12

**Comment by aVadim483** [comment] 2023-11-03 17:03
Fixed in the version v1.0.4
You need to update with composer for the dependencies to install

**Comment by lollita** [comment] 2023-11-03 18:01
I update with composer, but again I get:

`<b>Fatal error</b>:  Uncaught Exception: Errore (Codice 2) - XMLReader::open(zip://C:\Test\Test.xlsx#xl/worksheets/sheet4.xml): Failed to open stream: operation failed in K:\Gemma\vendor\avadim\fast-excel-reader\src\FastExcelReader\Reader.php linea 109`

error in sheet4.xml?

**Comment by lollita** [comment] 2023-11-03 21:14
Now updated to v1.0.4 but again not work:

`Fatal error: Uncaught Exception: Errore (Codice 2) - XMLReader::open(zip://C:\test/mode/test.xlsx#xl/worksheets/sheet4.xml): Failed to open stream: operation failed in C:\test\vendor\avadim\fast-excel-reader\src\FastExcelReader\Reader.php linea 109 in C:\test\common.php:22 Stack trace: #0 [internal function]: warningHandler(2, 'XMLReader::open...', 'C:\\test\\vendor...', 109) #1 C:\test\vendor\avadim\fast-excel-reader\src\FastExcelReader\Reader.php(109): XMLReader->open('zip://C:\\test/...', NULL, 0) #2 C:\test\vendor\avadim\fast-excel-templator\src\FastExcelTemplator\Excel.php(52): avadim\FastExcelReader\Reader->openZip('xl/worksheets/s...') #3 C:\test\vendor\avadim\fast-excel-templator\src\FastExcelTemplator\Excel.php(41): avadim\FastExcelTemplator\Excel->_importSheets() #4 C:\test\vendor\avadim\fast-excel-templator\src\FastExcelTemplator\Excel.php(79): avadim\FastExcelTemplator\Excel->__construct('C:\\test/modell...', NULL, Array) #5 C:\test\calc.php(724): avadim\FastExcelTemplator\Excel::template('C:\\test/modell...') #6 C:\test\calc.php(491): exportNucleoCrisi('127809,127810', false, 'false', false) #7 {main} thrown in C:\test\common.php on line 22
`

**Comment by aVadim483** [comment] 2023-11-04 09:05
You are trying to open your own file as a template, am I right?

The library sees that there should be sheet 4 in this file, but for some reason it cannot open it. Perhaps the file was not created in MS Excel, or it is damaged for some reason. If the file does not contain secret data, then you can send it to me, I will check what the problem is

**Comment by lollita** [comment] 2023-11-04 10:01
How to send the file to you?
Ty advanced.

**Comment by aVadim483** [comment] 2023-11-04 10:34
> How to send the file to you?

vadim483@gmail.com

**Comment by lollita** [comment] 2023-11-04 13:05
Sent.

**Comment by aVadim483** [comment] 2023-11-04 16:20
Well, I see error

**Comment by aVadim483** [comment] 2023-11-04 16:37
@lollita fixed in v.1.0.5

**Comment by lollita** [comment] 2023-11-04 17:16
again error in v1.0.5

```
<br />
<b>Warning</b>:  XMLReader::open(zip://C:/test/modelli/test.xlsx#xl/worksheets/sheet4.xml): Failed to open stream: operation failed in <b>C:/test\vendor\avadim\fast-excel-reader\src\FastExcelReader\Reader.php</b> on line <b>109</b><br />
<br />
<b>Warning</b>:  XMLReader::open(): Unable to open source data in <b>C:/test\vendor\avadim\fast-excel-reader\src\FastExcelReader\Reader.php</b> on line <b>109</b><br />
<br />
<b>Fatal error</b>:  Uncaught Error: Data must be loaded before reading in C:/test\vendor\avadim\fast-excel-templator\src\FastExcelTemplator\Reader.php:32
Stack trace:
#0 C:/test\vendor\avadim\fast-excel-templator\src\FastExcelTemplator\Reader.php(32): XMLReader-&gt;read()
#1 C:/test\vendor\avadim\fast-excel-templator\src\FastExcelTemplator\Excel.php(53): avadim\FastExcelTemplator\Reader-&gt;read()
#2 C:/test\vendor\avadim\fast-excel-templator\src\FastExcelTemplator\Excel.php(41): avadim\FastExcelTemplator\Excel-&gt;_importSheets()
#3 C:/test\vendor\avadim\fast-excel-templator\src\FastExcelTemplator\Excel.php(79): avadim\FastExcelTemplator\Excel-&gt;__construct('c:\\test/modell...', NULL, Array)
#4 C:/test\calc.php(735): avadim\FastExcelTemplator\Excel::template('c:\\test/modell...')
#5 C:/test\calc.php(502): test('', false, 'false', false)
#6 {main}
  thrown in <b>C:/test\vendor\avadim\fast-excel-templator\src\FastExcelTemplator\Reader.php</b> on line <b>32</b><br />

```

**Comment by aVadim483** [comment] 2023-11-04 17:43
Are you sure all dependencies are updated? You need to update the library via composer
```
composer update
```

**Comment by lollita** [comment] 2023-11-04 18:06
I now have updated all 4 packet:
fast-excel-writer, fast-excel-templator, fast-excel-reader, fast-excel-reader.
```
<b>Fatal error</b>:  Uncaught Exception: Errore (Codice 2) - XMLReader::open(zip://C:/test/modelli/test.xlsx#xl/worksheets/sheet4.xml): Failed to open stream: operation failed in C:/test\vendor\avadim\fast-excel-reader\src\FastExcelReader\Reader.php linea 109 in C:/test\common.php:22
Stack trace:
#0 [internal function]: warningHandler(2, 'XMLReader::open...', 'C:\\test\\vendor...', 109)
#1 C:/test\vendor\avadim\fast-excel-reader\src\FastExcelReader\Reader.php(109): XMLReader-&gt;open('zip://C:\\test/...', NULL, 0)
#2 C:/test\vendor\avadim\fast-excel-templator\src\FastExcelTemplator\Excel.php(52): avadim\FastExcelReader\Reader-&gt;openZip('xl/worksheets/s...')
#3 C:/test\vendor\avadim\fast-excel-templator\src\FastExcelTemplator\Excel.php(41): avadim\FastExcelTemplator\Excel-&gt;_importSheets()
#4 C:/test\vendor\avadim\fast-excel-templator\src\FastExcelTemplator\Excel.php(79): avadim\FastExcelTemplator\Excel-&gt;__construct('c:\\test/modell...', NULL, Array)
#5 C:/test\calc.php(735): avadim\FastExcelTemplator\Excel::template('C:\\test/modell...')
#6 C:/test\calc.php(502): test()
#7 {main}
  thrown in <b>C:/test\test.php</b> on line <b>22</b><br />

```

**Comment by aVadim483** [comment] 2023-11-04 18:25
I see in your error trace:
vendor\avadim\fast-excel-reader\src\FastExcelReader\Reader.php(109)

But this is empty line in the actual repo:
https://github.com/aVadim483/fast-excel-reader/blob/main/src/FastExcelReader/Reader.php#L109

So, you use not last version

**Comment by lollita** [comment] 2023-11-04 18:35
maybe I have to wait to update.
composer:
```
avadim/fast-excel-helper v1.0.5  Helper for avadim/fast-excel-reader and avadim/fast-excel-writer
avadim/fast-excel-reader v2.12.0 Lightweight and very fast XLSX Excel Spreadsheet Reader in PHP
avadim/fast-excel-writer v4.8.3  Lightweight and very fast XLSX Excel Spreadsheet Writer in PHP
```

**Comment by lollita** [comment] 2023-11-04 19:03
I have removed and reinstalled clean, and now it work.
I have only a memory problem _ini_set('memory_limit', '256M');_.
Ty.

**Closed as completed** 2024-04-07 09:03 UTC
